### ISSUE TITLE
HTTP Server does not start

### ISSUE THREAD

**Issue by Mdleal** [fritz-smh/yi-hack#10]
Everything looks good in the log. Debug is on. log_http.txt is empty.  'ps' does not show serverJ running.  I can not browser to camera's IP address.

`Start http server : serverJ...
Check for http server process : `

If I manually run ./serverJ 80
`# ./serverJ 80
Segmentation fault
`

**Comment by fritz-smh** [comment]
Hi,

It seems that the firmware M has not been applyied. Do you have the 'home' file at the root of your sdcard ?

Is the ftp server up ?

++

**Comment by Mdleal** [comment]
that did it. I had an old home file on the sd card
