### ISSUE TITLE
"Waiting to connect" Orange light blinking

### ISSUE THREAD

**Issue by cdb8457** [fritz-smh/yi-hack#128]
I apologize this is my first time setting this thing up ever, and on top of that with a hack.

These are the steps I took:

Formatted my SD card

Downloaded the zip file

put 

![image](https://cloud.githubusercontent.com/assets/21016001/22350114/7681c14e-e3c7-11e6-8f5e-dfe5d9cb4c58.png)

SD file on the SD card

Changed the SSID and Password and Static

![image](https://cloud.githubusercontent.com/assets/21016001/22350189/a95dafba-e3c7-11e6-91b8-8755be4e78f9.png)

![image](https://cloud.githubusercontent.com/assets/21016001/22350220/cd1b579a-e3c7-11e6-9eab-c292c8c37f48.png)

Saved

Then I took the SD card out put it in the YI cam. Plugged it in. Orange Blinking light

Version is YHS -113-IR

**Comment by hyptechdev2015** [comment]
![explorer_2017-01-26_21-10-36](https://cloud.githubusercontent.com/assets/13682268/22361176/1ec8d0ba-e40c-11e6-881f-14b4d07a68f5.png)

make sure only add "home", and test folder to newly formatted SD card (SD should be formatted to FAT32)

**Comment by cdb8457** [comment]
OK, those are in the same file behind that Test file.  

If I have 

![image](https://cloud.githubusercontent.com/assets/21016001/22401427/4b1caaa0-e598-11e6-9e0e-c2e49444ff45.png)

Do i need to change it from TKIP to WPA Personal?

![image](https://cloud.githubusercontent.com/assets/21016001/22401435/a3c13e64-e598-11e6-89d3-7c80a467fa87.png)

**Comment by cdb8457** [comment]
If its yellow blinking does mean it cant connect? I if figure this out. I might make a YouTube video explaining it to my dumb self.

**Comment by cdb8457** [comment]
Ok, my mistake. Got it to FAT32 and made sure it only had Test and home on it. It seems like its still on yellow blinking light.

**Comment by cdb8457** [comment]
It starts as yellow solid light. Then starts blue blinking. Two Clicks, blue blinking, Blue solid for like a few seconds, then finishes with yellow blinking. Any help?

**Comment by asmile60** [comment]
same with me here at first is ok nothing problem after use for few days and then suddenly the image is upside down, and I restart the camera, and now yellow blinking after solid blue.

**Comment by qelanhari** [comment]
I don't know if it's your problem, but remember that the camera only connects to 2.4ghz wifi, not 5ghz.

**Comment by cdb8457** [comment]
Thanks for the responds. I have only been connecting to the 2.4ghz. I am going to try again sometime soon.

**Comment by death2all110** [comment]
Can you post a copy of the log file? Should be on the SD in the test folder.

**Comment by cdb8457** [comment]
![image](https://cloud.githubusercontent.com/assets/21016001/22620253/784dcce2-eabc-11e6-8609-70174cd4311f.png)

![image](https://cloud.githubusercontent.com/assets/21016001/22620256/949cc9ac-eabc-11e6-8a44-fe89e3270e52.png)

![image](https://cloud.githubusercontent.com/assets/21016001/22620259/a946ba8e-eabc-11e6-80cc-d0aa291f5f42.png)


Sorry for the late response. I appreciate the help!

**Comment by death2all110** [comment]
@cdb8457 I see the issue.

in wpa_supplicant.conf you need single quotes around the SSID and PSK
Example:

```
...
SSID='ManCave'
...
PSK='Vikings@58'
...
```

**Comment by cdb8457** [comment]
Well...That is slightly embarrassing . I will Try that today......

**Comment by cdb8457** [comment]
Well I have given up. I have done everything correct. It get to the last blue light. Hangs for a little bit then goes to yellow blinking.

**Comment by death2all110** [comment]
Can you post the log? Are you using the same equip_test.sh in this repo, or my fork, or an edited version? You can post the log to gist.github.com and then share the link here, that will make it easier.

**Comment by cdb8457** [comment]
<script src="https://gist.github.com/cdb8457/c8b483d14584c075bf9a3d6bd00eebc0.js"></script>

I believe I am using the one that is in the zip on this git hub page.

**Comment by cdb8457** [comment]
[c8b483d14584c075bf9a3d6bd00eebc0-b864f8e44dcf2627857b7662848a323f1cd380d2.zip](https://github.com/fritz-smh/yi-hack/files/756373/c8b483d14584c075bf9a3d6bd00eebc0-b864f8e44dcf2627857b7662848a323f1cd380d2.zip)

**Comment by cdb8457** [comment]
I apologize with trying to get this log on here. Can you view it?

[log.txt](https://github.com/fritz-smh/yi-hack/files/756377/log.txt)

**Comment by death2all110** [comment]
@cdb8457 Sorry for the late reply!


I actually advised you incorrectly on you wpa_supplicant.conf. My aplogies.

Try using quotes instead of single quotes.

```
...
SSID="ManCave"
...
PSK="Vikings@58"
...
```

**Comment by cdb8457** [comment]
I tired it and thought it was going to work .....it did the blue blinking for a lot longer this time. I will keep trying. Now I have never flashed anything on it. All I have ever done is put those files on the sd card.

**Comment by cdb8457** [comment]
Is there supposed to be talking to me while this sets up? There is none.

**Comment by death2all110** [comment]
@cdb8457 it didnt play any sound at all during boot?

Remove the files from the SDCard temporarily, re-format to fat32 and place the files back on and put it back in the camera. 

Also, just to make sure, you did double quotes right? because the actual quotation marks `"` is seen as 1 character where as two single quotes `''` is seen as two.

**Comment by cdb8457** [comment]
I used Shift + '  ="   I used " that.

**Comment by death2all110** [comment]
@cdb8457 ok good, just making sure.

So at this point, what I recommend doing is: 

- unplug the camera
- remove the sd from the camera
- move the files from the SDCard temporarily
- re-format the sd to fat32 
- place the files back on the sd 
- put the sd back in the camera
- plug the camera in.

If that still doesn't work, please attach the log file as you did before.

**Comment by cdb8457** [comment]
[log.txt](https://github.com/fritz-smh/yi-hack/files/765230/log.txt)

No sound when starting up. Just Clicks noises. Just did what was above

**Comment by death2all110** [comment]
What color is the LED?

According to the log, the wifi is connected.

**Comment by cdb8457** [comment]
It starts as orange solid, Clicks, blue blinking, clicks twice. blue blinking for a bit. Then solid blue for 8 seconds, then goes back to blinking orange forever.

**Comment by death2all110** [comment]
Now that I think of it, has the sound worked at all? Because the path to the voice files in equip_test.sh is actually incorrect it all points to /home/hd1/voice instead of /home/hd1/test/voice.

2 options. move the voice subfolder to the root of the SD, or correct the paths in the script by following [this commit.](https://github.com/fritz-smh/yi-hack/pull/106/commits/d549a48a726a5e6a718e1b17a8430f865b894806)

**Comment by cdb8457** [comment]
![image](https://cloud.githubusercontent.com/assets/21016001/22807530/59448830-eedc-11e6-971f-1734415af8d9.png)
 This is what Happens after I start up. New files pop up.

**Comment by death2all110** [comment]
I'm guessing the reason for the orange blinking is that the last ping command is failing. 

In equip_test.sh you will see the following lines:
```
### Check if reach gateway and notify
ping -c1 -W2 $(get_config GATEWAY) > /dev/null
if [ 0 -eq $? ]; then
    led $(get_config LED_WHEN_READY)
    /home/rmm "/home/hd1/voice/success.g726" 1
else
    led -boff -yfast
fi
```

go ahead and change to the following:

```
### Check if reach gateway and notify
###ping -c1 -W2 $(get_config GATEWAY) > /dev/null
###if [ 0 -eq $? ]; then
    led $(get_config LED_WHEN_READY)
    /home/rmm "/home/hd1/voice/success.g726" 1
###else
###    led -boff -yfast
###fi
```
Also, to fix the voice you have 2 options. move the voice subfolder to the root of the SD, or correct the paths in the script by following [this commit.](https://github.com/fritz-smh/yi-hack/pull/106/commits/d549a48a726a5e6a718e1b17a8430f865b894806)

**Comment by cdb8457** [comment]
![image](https://cloud.githubusercontent.com/assets/21016001/22807961/931928de-eede-11e6-8027-1442cf074109.png)
 hmm"Else is not even on mine.

**Comment by death2all110** [comment]
Theres actually 2 ping sections the one I'm referring to is the second one near line 399. The section you screenshot is the first one.

**Comment by cdb8457** [comment]
k, fix both things!

**Comment by death2all110** [comment]
Awesome! Glad to hear it man! You should see a button to mark the issue as closed. Have a great day!

**Comment by cdb8457** [comment]
How did those files get changed?...Did i do it?

**Comment by cdb8457** [comment]
Thanks for the Help!

**Comment by death2all110** [comment]
@cdb8457 Nah, the equip_test.sh has the wrong paths for sound to begin with.

**Comment by Structure3creative** [comment]
Had same issue. Did the above with audio of successful pairing. Solid blue LED, webpage won't load. No ping.

**Comment by ITSolution4U** [comment]
Please watch this video for Solution.
https://www.youtube.com/watch?v=ZaKGDeC4_oM
