### ISSUE TITLE
How to view rstp steam?

### ISSUE THREAD

**Issue by cdb8457** [fritz-smh/yi-hack#132]
I have no clue on how to look at this Yi cam. 

![image](https://cloud.githubusercontent.com/assets/21016001/22810274/918a71b8-eeec-11e6-8175-a55528a2d458.png)

I get to this, but none of the blue links work.

**Comment by ghost** [comment]
Did you ever figure out how to view the rtsp stream or get the links to work? Same issue here.

**Comment by joozy** [comment]
You'd usually use a video viewer, VLC, is a popular one.

Open Network Stream
Enter rtsp://cameraip:port/ch0_0.h264 or ch0_1.h264 or ch0.264.

**Comment by ghost** [comment]
I've tried the [VXG Player](https://www.videoexpertsgroup.com/o/chrome-media-player-plug-in/) and the furthest it has gone is an image still. Will [VLC](http://www.videolan.org/vlc/) work similarly?
 
The server page loads, and none of the links connect to the stream, motion, or record.

**Comment by joozy** [comment]
I'm getting a live video stream from mine, throug VLC.
Have not tried VXG.

I've noted there was an issue, from this github, that the live stream will "terminate" after X minutes eventhough the camera was still running (the user could telnet into the camera).

Update:
Just tried VXG and appears to work...only thing was the default VXG webpage provides a fixed window size and regardless of _0.h264 or _1.h264 the video was the fixed video window size.
