### ISSUE TITLE
Include secure Curl

### ISSUE THREAD

**Issue by utya1988** [fritz-smh/yi-hack#143]
Hello. A lot of thanks for this hack. I would like to how i can include secure curl in home file. O maybe you can make branch with this feature. Vey Thanks.

**Comment by karepiu** [comment]
Use this http://nemon.org/ipcam-ipr1631x/#SDK to compile curl from scratch. You will need also openssl. I can confirm that curl-7.53.1 and opessl-1.1.0e works fine. In 3 weeks I hope to branch fritz code adding curl, lighttpd, samba, smartthings capabilities.

**Comment by utya1988** [comment]
@karepiu , maybe can you complie ffmpeg. I tried but failed.

**Comment by karepiu** [comment]
HI, compiled it with --enable-shared --disable-yasm. Have not tested it but should work. Working dit should be /tmp/ffmpeg.  Good luck!

https://www.dropbox.com/s/6s009nfchafndbh/ffmpeg-3.2.4-arm.tar.gz?dl=0

**Comment by utya1988** [comment]
@karepiu, thanks.

**Comment by gl-lamhnguyen** [comment]
@utya1988 did you solve the issue with secured curl? I kept getting ssl not supported in the current version

**Comment by karepiu** [comment]
Compile openssl first, then point compilator for curl to its dirs and it works like a charm.

**Comment by gl-lamhnguyen** [comment]
@karepiu thx for the info, I'm not really sure how to compile it? is there a binary somewhere I can download and copy it to the SD card?
