### ISSUE TITLE
Telnet Record On/Off via Tasker

### ISSUE THREAD

**Issue by anndrewww** [fritz-smh/yi-hack#148]
I'd like to create a shell script (telnet) to toggle the camera's recording/motion detection checks On/Off (eventually via Tasker). If anyone can point me in the right direction or provide some coding assistance, it would be much appreciated.

**Comment by utya1988** [comment]
it's project with web, when you can enable/disable some service, it's very useful for undertanding.
https://github.com/SnakeSel/YiHome_camera_http

**Comment by nxsfan** [comment]
In my pull request you can control services from the web interface:
https://github.com/nxsfan/yi-hack
https://github.com/fritz-smh/yi-hack/pull/102
