### ISSUE TITLE
Can we remove the microSD card after installation ?

### ISSUE THREAD

**Issue by SeraphicRav** [fritz-smh/yi-hack#16]
Hi !

My issue is actually a simple question. Once the new firmware is installed, can we remove the microSD ? I only use the camera to stream to a server.

Thank you for your hard work !

**Comment by fritz-smh** [comment]
No, you must keep the SD card. If you remove it, the camera will work as before (cloud, ...)

The idea was to be able to rollback easily the camera to its classic mode just by removing the sd card
