### ISSUE TITLE
Clarification on cloud and app features

### ISSUE THREAD

**Issue by claytonrothschild** [fritz-smh/yi-hack#160]
I understand that the readme for this hack states:

This feature is removed: "send video data over the network on Chinese servers in the cloud to allow people to view camera data from their smartphone wherever they are." and therefore there is "no more need to use a smartphone application."

Is the app still operable when used on the same local network as the camera, or is the only way to view live footage through the RTSP stream? 

Thank you.

**Comment by death2all110** [comment]
The only way to view live footage with this fw is through rtsp.

**Comment by death2all110** [comment]
@claytonrothschild my fork has the app enabled.
