### ISSUE TITLE
Blurry Video

### ISSUE THREAD

**Issue by ghost** [fritz-smh/yi-hack#177]
Are there any options to set advanced video parameters such as brightness/sharpness/bitrate etc? I tried changing the file /etc/ui.conf but it doesn't seem that this file does anything at all anymore.
I've seen many scripts for the Yi action camera that seems similar to what I'm trying to accomplish but nothing for the "home/ant" cameras. Any help would be appreciated.

**Comment by keith721** [comment]
Is it perhaps a focus/lens issue?  If so, disassemble the camera, remove the glue from the lens threads which locks it in place, and while viewing live video from the camera, gently turn the lens in either direction until you get the most clear image.

**Comment by ghost** [comment]
I just tried and it makes a HUGE difference. It's so sharp now that I may have to dial it back a bit since the sharpness does not play well with the low the bitrate from the feedis, but it looks so much better!

Thanks for the tip! 

![before-after](https://user-images.githubusercontent.com/1346977/27256956-1ac01486-5394-11e7-98b1-c65dd6e70f08.gif)

**Comment by querex007** [comment]
Damn what a hudge difference, thanks for the tip!
