### ISSUE TITLE
Won't flash after other custom firmware

### ISSUE THREAD

**Issue by blawford** [fritz-smh/yi-hack#216]
Seems this project isn't really maintained anymore, but worth a shot.

Trying to flash this firmware after installing another (shadow-1's yi-hack-v3) and putting the contents of the sd folder in the root of my SD card doesn't have any effect.

I have also tried reverted to the stock firmware, setup the camera again where it asked me if I wanted to update the firmware, which I did. Then inserting a SD card with this on seems to take me back to the v3 variant? So I guess the shadow version is never being overwritten no matter what I try.

Anyone any ideas of what I can try? Specifically after RTSP so shadow's isn't going to cut it.

**Comment by lance36** [comment]
what camera model have you got?

**Comment by blawford** [comment]
The home 1080p v1 (bought from Amazon UK).

**Comment by blawford** [comment]
Anyone?

**Comment by LordVanguard** [comment]
Did you ever find out Blawford ? I'm in the same boat but with the Yi-Home 720p 47US version. Wanted RTSP but only saw this after visiting the V3 hack .... now I cannot change to any other.

**Comment by blawford** [comment]
I did get it working. Not sure the stability of the RTSP stream was worth it but that might have just been me.

Managed to flash the original firmware (stored by the author of the v3) and the follow the instructions for this one.

On 22 Dec 2018 20:35, LordVanguard <notifications@github.com> wrote:

Did you ever find out Blawford ? I'm in the same boat but with the Yi-Home 720p 47US version. Wanted RTSP but only saw this after visiting the V3 hack .... now I cannot change to any other.

**Comment by LordVanguard** [comment]
Thanks for the quick response, much appreciated. 

Did try the rescue flash but for some reason it didnt seem to take. Will go for a different SD and see if it makes a difference. 

Thanks again

**Comment by blawford** [comment]
Post again if you can't get it working and I will give you more detail.

On 22 Dec 2018 20:58, LordVanguard <notifications@github.com> wrote:

Thanks for the quick response, much appreciated.

Did try the rescue flash but for some reason it didnt seem to take. Will go for a different SD and see if it makes a difference.

Thanks again
