### ISSUE TITLE
Yi-Hack + Appli Xiaomi

### ISSUE THREAD

**Issue by k4r4su** [fritz-smh/yi-hack#26]
Bonjour,
Quels sont les fichiers à éditer afin de pouvoir profiter d'un coté du Yi-Hack, et de l'autre pouvoir toujours utiliser l'appli Xiaomi ?
Je trouve pratique le fait de pouvoir visualiser les moments où un mouvement à été detecté, ce que malheureusement, ton hack ne propose pas (encore :)).

Merci de ta réponse 
@+

**Comment by fritz-smh** [comment]
Salut, désolé pour le délai de réponse.
J'ai carrément viré les appels à ces process du script, il faudrait donc les rajouter 

Après l'appel à : 
./mp4record 60 &

Ajoute ceci :
#       ./p2pserver &
        ./cloud &

Si ça ne passe pas, décommente la ligne p2pserver
