### ISSUE TITLE
ability to turn on remote connection, or have two versions available

### ISSUE THREAD

**Issue by samo-nz** [fritz-smh/yi-hack#36]
I want to have all the abilities you added but also allow it to connect to Xiaomi's servers, is there a way to turn them back on or can you provide a seperate version with remote connection enabled?

**Comment by fritz-smh** [comment]
Sorry, this firmware goal was to not avoid the cloud anymore.

What you can try is putting back the calls to p2pserver, cloud and watch_process processes in the script by comparing to the original script
