### ISSUE TITLE
Lock down access to camera

### ISSUE THREAD

**Issue by samo-nz** [fritz-smh/yi-hack#37]
Currently anyone on the network can open the camera download files etc, each feature should be able to be locked down with a password or turned off. 

The best way to achieve this would be to have a settings link on the web-server that requires a user to log in, and all settings are managed there.

**Comment by fritz-smh** [comment]
Hi,

This is indeed a good idea, but I have no idea on how I can do that. I have not the web server sources (and more over I am not familiar with cross compilation tools...)

I close the ticket but if anybody got an idea, feel free :)

**Comment by fz883** [comment]
Simply turn off the webserver by prepending a "#" to the lines 341, 343 and 347.
