### ISSUE TITLE
Xiaomi ants 2 ?

### ISSUE THREAD

**Issue by TommyChausson** [fritz-smh/yi-hack#38]
Hi, 

Is this hack usable with the second version of the xiaomi ants ?

Regards,

**Comment by fritz-smh** [comment]
Hi,

I am sure it will not be compliant as the hardware will be different. Maybe we could use the same tricks, but I have not such a camera with me today :(

++

**Comment by TommyChausson** [comment]
Just in case... to tell the others : Niclet is working on it here :https://github.com/niclet/yi-hack-v2
