### ISSUE TITLE
European Version

### ISSUE THREAD

**Issue by pbriesch** [fritz-smh/yi-hack#46]
Hello,

first, this is not an issue.

I have the European version of the camera and I'm wondering if I could help a little bit by offering remote access to the camera's console via Internet.

Regards, Paul

**Comment by kot7k** [comment]
I dont really know if the european version works the same as the chinese version, you could just try the script cause it doesn't modify system files, just loads all the parameters from the sd card. (well it actually modifys the name of a sound file wich moans in chinese, but its the only thing).
If it doesnt work, just delete it from sd and thats it.
If it works you could telnet to your camera from internet by opening the corresponding port on your router. FOR EXAMPLE, you could forward port 9531 to the port 23 of your camera so when you telnet <yourinternetaddres> 9531 , your router will redirect you to <ipaddresofyourcamera> <port23> and you could log in.
