### ISSUE TITLE
Configuration NTP

### ISSUE THREAD

**Issue by byanou69** [fritz-smh/yi-hack#5]
Serait-ce possible de paramétrer un serveur NTP spécifique dans le fichier de config ?
Celà permet d'utiliser un NTP local et non publique.
Merci

**Comment by fritz-smh** [comment]
oui, je ferais ça dans les jours qui viennent. Si tu n'as pas de news d'ici une semaine, remet un commentaire ici pour m'y refaire penser ;)

**Comment by byanou69** [comment]
So perfect !
Merci msieur c'est topissime !
