### ISSUE TITLE
Compatibility with Xiaomi yi 360?

### ISSUE THREAD

**Issue by ilianvlm** [fritz-smh/yi-hack#83]
There's a new version of this [camera that has pan and tilt "panorama".](http://www.gearbest.com/ip-cameras/pp_356786.html)

Is there a compatible version of the yi-hack in the works?

**Comment by fritz-smh** [comment]
Hi, no, there is not

**Comment by Awk34** [comment]
Hi, @fritz-smh. I saw that there's a different pan-tilt surveillance camera here:https://www.amazon.com/dp/B01CW4BN5M. It also has an SD card slot. Do you think a similar hack would work for this camera?
